### ISSUE TITLE
File upload message box

### ISSUE THREAD

**Issue by thewilloftheshadow** [Swishilicous/grammar-nazi#10]
When sending a message through the file upload box, Grammar Nazi doesn't take effect. The message stays as you typed it, even after checking if it's enabled

**Comment by Swishilicous** [comment]
Yeah, I've known this since I first released this plugin. The module I'm using to change messages before they're sent doesn't work when you embed a file.

At the current time I have zero idea how I would fix this but I'll leave it open as it is an issue.
