### ISSUE TITLE
Can't use Grammar-Nazi anymore

### ISSUE THREAD

**Issue by ShiiroSan** [Swishilicous/grammar-nazi#8]
If the plugin is on, when I send a message nothing is sent. Under is a screenshot of the error I get in Discord Console when I send a message.
https://i.shii.ro/z9A362Mg.jpg

**Comment by tyush** [comment]
Try pulling from the [best-wip](https://github.com/Swishilicous/grammar-nazi/tree/best-wip) branch and try again, this will be fixed when the best-wip branch gets merged with the main branch.
