### ISSUE TITLE
Custom dictionary doesn't work

### ISSUE THREAD

**Issue by thewilloftheshadow** [Swishilicous/grammar-nazi#9]
The custom dictionary isn't functioning as it should. The setting is enabled in the settings menu and in the json settings file (just to be super sure) but it doesn't replace. I also am unable to use any of the three dictionary commands, as they either say I haven't given enough arguments or they just return empty. I've reloaded Discord and the plugin, and nothing has changed either.

**Comment by Swishilicous** [comment]
Oh that's my bad, I forgot to specify what arguments you need to use. I'll add that to the repository this afternoon.

For .naziadd you need two arguments, the word to replace and the word to replace it with. (both must be surrounded by quotes)

Examples:
.naziadd "to replace" "replace with"
.naziadd "key" "value"
.naziadd "doesnt" "doesn't"

For .naziremove you need to specify one argument, the "to replace" word that you specified in the dictionary earlier. (also surrounded by quotes)

Examples:
.naziremove "to replace"
.naziremove "key"
.naziremove "doesnt"

.meinkampf requires zero arguments.

Also, for future reference if you don't know how to use a command you can use the .help command built into powercord and it'll tell you the required input arguments.

**Comment by thewilloftheshadow** [comment]
Yea, I looked at the help and it didn't help. The quotes were what I was missing. Thanks!
